# Generated by Django 6.0.5 on 2026-06-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Astra_Market', '0004_order_shipping_address_order_shipping_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('changed_mind', 'Changed my mind'), ('found_cheaper', 'Found a cheaper option'), ('no_longer_needed', 'No longer needed'), ('delivery_too_slow', 'Delivery is too slow'), ('found_alternative', 'Found a better alternative'), ('shipping_expensive', 'Shipping is too expensive'), ('product_not_available', 'Product not available'), ('other', 'Other reason')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
