# Generated by Django 6.0.6 on 2026-06-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Astra_Market', '0007_order_order_number_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
